function sendEffectZone(zone)
    local zoneAreas = zone:getRange()
    
    for _, zoneArea in ipairs(zoneAreas) do
        local topLeft = zoneArea[1]
        local bottomRight = zoneArea[2]

        for x = topLeft.x, bottomRight.x do
            for y = topLeft.y, bottomRight.y do
                local pos = Position(x, y, 7)
                pos:sendMagicEffect(27)
                Game.createItem(2160, 1, pos)
                Game.sendAnimatedText(pos, "Zone Id:" .. zone:getId(), math.random(255))
            end
        end
    end

end

ACTIVE_ZONE_EVENT = false
ACTIVE_ZONE_EVENT_ID = 0
ACTIVE_ZONE_TYPE = ""
ACTIVE_ZONE_EVENT_RATE_LOOT = 1
ACTIVE_ZONE_NAME = ""

ZONE_YUGI = 9

ZONES_LOOT = {}
ZONES_LOOT_RATE = {2, 3}

CONST_CEU_ZONE = 1

function randomizeZoneEventLoot()
    if true then
        return
    end
	local newId = ZONES_LOOT[math.random(#ZONES_LOOT)]
	ACTIVE_ZONE_EVENT_ID = newId
	local zone = Game.getZoneById(newId) 
	if not zone then return error("[ZONE] Incorrect Zone Generated by event.") end
	ACTIVE_ZONE_EVENT = true
	ACTIVE_ZONE_TYPE = "loot"
	local newRate = ZONES_LOOT_RATE[math.random(#ZONES_LOOT_RATE)]
	ACTIVE_ZONE_EVENT_RATE_LOOT = newRate
	local zoneName = zone:getName()
	ACTIVE_ZONE_NAME = zoneName
	local message = string.format("[ZONES-EVENT] Foi ativado bônus de loot %dx na zona %s.", newRate, zoneName)
	broadcastMessage(message, MESSAGE_EVENT_ADVANCE)
end